#!/usr/bin/env python3
"""Migrate a ChatGPT export to a local, reviewable Obsidian knowledge base."""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any

from src.archive import archive_conversation, render_archive_indexes
from src.deduplicator import merge_candidate, remove_conversation, resolve_current_environment
from src.discovery import discover, format_inventory
from src.extractor import extract_memories
from src.normalizer import normalize_conversation
from src.obsidian import render_vault
from src.parser import ExportParseError, iter_json_array, parse_conversation
from src.preservation import inspect_export, mirror_export
from src.project_catalog import ProjectCatalogError, discover_github_repositories, discover_local_projects, replace_catalog_source
from src.report import write_reports
from src.resources import load_asset_catalog

STATE_FILE = ".chatgpt-migration-state.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert a local ChatGPT export into an evolving Obsidian knowledge base. GitHub is contacted only when --github-user is configured.")
    parser.add_argument("--source", required=True, type=Path, help="Extracted ChatGPT export directory (read only)")
    parser.add_argument("--output", required=True, type=Path, help="Destination Obsidian vault directory")
    parser.add_argument("--dry-run", action="store_true", help="Inspect and estimate output without creating or modifying the vault")
    parser.add_argument("--archive-conversations", action="store_true", help="Backward-compatible alias; searchable Markdown archives are generated by default")
    parser.add_argument("--projects-root", action="append", type=Path, help="Read-only local coding-project root to catalogue; saved for future refreshes")
    parser.add_argument("--github-user", action="append", help="GitHub user whose public repository metadata should be catalogued; saved for future refreshes")
    parser.add_argument("--watch", action="store_true", help="Repeat the incremental refresh until interrupted")
    parser.add_argument("--watch-interval", type=int, default=300, metavar="SECONDS", help="Seconds between --watch refreshes (default: 300)")
    parser.add_argument("--github-refresh-interval", type=int, default=3600, metavar="SECONDS", help="Minimum interval between GitHub checks in --watch mode (default: 3600)")
    return parser.parse_args()


def _safe_output(source: Path, output: Path) -> None:
    source, output = source.resolve(), output.resolve()
    if source == output or source in output.parents:
        raise ValueError("Output must not be the source directory or a directory inside it; this protects the original export.")


def _load_state(output: Path) -> dict[str, Any]:
    path = output / STATE_FILE
    if not path.is_file():
        return {"version": 5, "conversations": {}, "archives": {}, "archive_indexes": [], "memories": [], "project_catalog": [], "project_sources": {"local_roots": [], "github_users": [], "github_checked_at": {}}}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(value, dict) and isinstance(value.get("conversations"), dict) and isinstance(value.get("memories"), list):
            value.setdefault("archives", {})
            value.setdefault("archive_indexes", [])
            value.setdefault("project_catalog", [])
            value.setdefault("project_sources", {"local_roots": [], "github_users": [], "github_checked_at": {}})
            value["project_sources"].setdefault("local_roots", [])
            value["project_sources"].setdefault("github_users", [])
            value["project_sources"].setdefault("github_checked_at", {})
            value["version"] = 5
            if isinstance(value["archives"], dict) and isinstance(value["archive_indexes"], list) and isinstance(value["project_catalog"], list) and isinstance(value["project_sources"]["local_roots"], list) and isinstance(value["project_sources"]["github_users"], list) and isinstance(value["project_sources"]["github_checked_at"], dict):
                return value
    except (OSError, json.JSONDecodeError):
        pass
    return {"version": 5, "conversations": {}, "archives": {}, "archive_indexes": [], "memories": [], "project_catalog": [], "project_sources": {"local_roots": [], "github_users": [], "github_checked_at": {}}}


def _save_state(output: Path, state: dict[str, Any]) -> None:
    path = output / STATE_FILE
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")
    temporary.replace(path)


def run(args: argparse.Namespace) -> int:
    source, output = args.source.expanduser(), args.output.expanduser()
    _safe_output(source, output)
    inventory = discover(source)
    print(format_inventory(inventory))
    state = _load_state(output) if not args.dry_run else {"version": 5, "conversations": {}, "archives": {}, "archive_indexes": [], "memories": [], "project_catalog": [], "project_sources": {"local_roots": [], "github_users": [], "github_checked_at": {}}}
    memories: list[dict[str, Any]] = state["memories"]
    archive_paths: dict[str, str] = state["archives"]
    archive_indexes: list[str] = state["archive_indexes"]
    asset_catalog = load_asset_catalog(source)
    raw_estimate = inspect_export(source)
    stats: dict[str, Any] = {"source_files": [str(path.relative_to(source)) for path in inventory.all_files], "discovered": 0, "processed": 0, "skipped": 0, "duplicates": 0, "transcripts": 0, "raw_files": raw_estimate.files, "raw_bytes": raw_estimate.bytes, "raw_copied": 0, "raw_skipped": 0, "raw_removed": 0, "local_projects": 0, "github_projects": 0, "project_indexes": 0, "output_files": 0}
    errors: list[str] = []
    project_sources = state["project_sources"]
    local_roots = list(dict.fromkeys([str(Path(value).expanduser().resolve()) for value in project_sources["local_roots"]] + [str(path.expanduser().resolve()) for path in (getattr(args, "projects_root", None) or [])]))
    github_users = list(dict.fromkeys([str(value).strip() for value in project_sources["github_users"] + (getattr(args, "github_user", None) or []) if str(value).strip()]))
    catalog = list(state["project_catalog"])
    for root in local_roots:
        try:
            catalog = replace_catalog_source(catalog, discover_local_projects([Path(root)]), "local", root)
        except ProjectCatalogError as exc:
            errors.append(str(exc))
    checked_at = dict(project_sources["github_checked_at"])
    now = int(time.time())
    github_refresh_interval = getattr(args, "github_refresh_interval", 3600)
    for username in github_users:
        last_check = checked_at.get(username)
        watch_refresh_due = not getattr(args, "watch", False) or not isinstance(last_check, int) or now - last_check >= github_refresh_interval
        if not watch_refresh_due:
            continue
        try:
            catalog = replace_catalog_source(catalog, discover_github_repositories(username), "github", username)
            checked_at[username] = now
        except ProjectCatalogError as exc:
            errors.append(str(exc))
    state["project_catalog"] = catalog
    state["project_sources"] = {"local_roots": local_roots, "github_users": github_users, "github_checked_at": checked_at}
    stats["local_projects"] = sum(project.get("catalog_source") == "local" for project in catalog)
    stats["github_projects"] = sum(project.get("catalog_source") == "github" for project in catalog)
    total_files = len(inventory.conversation_files)
    for file_index, path in enumerate(inventory.conversation_files, 1):
        print(f"Processing file {file_index}/{total_files}: {path.name}")
        try:
            records = iter_json_array(path)
            for record_index, record in enumerate(records, 1):
                stats["discovered"] += 1
                try:
                    conversation = normalize_conversation(parse_conversation(record, str(path.relative_to(source))))
                    previous = state["conversations"].get(conversation["id"])
                    if previous == conversation["fingerprint"]:
                        if not args.dry_run:
                            archived = archive_conversation(output, conversation, previous_relative=archive_paths.get(conversation["id"]), catalog=asset_catalog)
                            archive_paths[conversation["id"]] = archived.relative_to(output).as_posix()
                            stats["transcripts"] += 1
                        stats["skipped"] += 1
                        continue
                    # An updated conversation replaces its old candidates before being merged.
                    if previous:
                        remove_conversation(memories, conversation["id"])
                    candidates = extract_memories(conversation)
                    for candidate in candidates:
                        if merge_candidate(memories, candidate):
                            stats["duplicates"] += 1
                    state["conversations"][conversation["id"]] = conversation["fingerprint"]
                    stats["processed"] += 1
                    if not args.dry_run:
                        archived = archive_conversation(output, conversation, previous_relative=archive_paths.get(conversation["id"]), catalog=asset_catalog)
                        archive_paths[conversation["id"]] = archived.relative_to(output).as_posix()
                        stats["transcripts"] += 1
                except (ExportParseError, TypeError, ValueError, KeyError) as exc:
                    stats["skipped"] += 1
                    errors.append(f"{path.name} record {record_index}: {type(exc).__name__}: {exc}")
                if record_index % 250 == 0:
                    print(f"  Conversations processed: {stats['processed']}; memories: {len(memories)}; duplicates merged: {stats['duplicates']}; errors: {len(errors)}")
        except (OSError, ExportParseError) as exc:
            errors.append(f"{path.name}: {type(exc).__name__}: {exc}")
    if args.dry_run:
        print("\nDry run complete.")
        print(f"Conversations: {stats['discovered']}")
        print(f"Potential memory candidates: {len(memories)}")
        print(f"Potential projects: {sum(memory['category'] == 'project' for memory in memories)}")
        print(f"Local coding projects: {stats['local_projects']}")
        print(f"Public GitHub repositories: {stats['github_projects']}")
        print(f"Raw export mirror: {stats['raw_files']} files, {stats['raw_bytes']} bytes")
        print(f"Errors: {len(errors)}")
        return 0
    resolve_current_environment(memories)
    output.mkdir(parents=True, exist_ok=True)
    mirror = mirror_export(source, output)
    stats.update({"raw_files": mirror.files, "raw_bytes": mirror.bytes, "raw_copied": mirror.copied, "raw_skipped": mirror.skipped, "raw_removed": mirror.removed})
    created = render_vault(output, memories, stats, archive_paths, catalog)
    stats["project_indexes"] = sum(path.parent == output / "Projects" and path.name != "Projects Index.md" for path in created)
    state["archive_indexes"] = render_archive_indexes(output, archive_paths, archive_indexes)
    stats["output_files"] = len(created) + len(state["archive_indexes"]) + 2 + mirror.copied
    created.extend(write_reports(output, stats, memories, errors))
    _save_state(output, state)
    print("\nMigration complete.")
    print(f"Conversations processed: {stats['processed']}; unchanged skipped: {stats['skipped']}; memories: {len(memories)}; duplicates merged: {stats['duplicates']}; errors: {len(errors)}")
    print(f"Vault: {output.resolve()}")
    return 0


def main() -> int:
    try:
        args = parse_args()
        if args.watch_interval < 1:
            raise ValueError("--watch-interval must be at least 1 second")
        if args.github_refresh_interval < 1:
            raise ValueError("--github-refresh-interval must be at least 1 second")
        if args.dry_run and args.watch:
            raise ValueError("--watch cannot be combined with --dry-run")
        if not args.watch:
            return run(args)
        while True:
            result = run(args)
            if result:
                return result
            print(f"Watching for changes; next refresh in {args.watch_interval} seconds. Press Ctrl+C to stop.")
            time.sleep(args.watch_interval)
    except (FileNotFoundError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
